config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'books/new'
  get '/top' => "homes#top"
  get 'books' => 'books#index', as: 'index_book'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
     if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book)
     else
      @books = Book.all
      render :index
     end
  end

  def index
    @books = Book.all
    @book = Book.new(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = 'Book was successfully update.'
     else
      render :edit
     end
  end

  def destroy
    book = Book.find(params[:id])
    flash[:notice] = 'Book was successfully destroyed.'
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <p><%= f.submit 'Update Book' %></P>

   <P>
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", "/books" %>
   </p>
  

<% end %>

app/views/books/index.html.erb
<%= flash[:notice] %>
<body>
   <h1>Books</h1>
    <table>
      <thead>
          <tr>
             <th>Title</th>
             <th>Body</th>
             <th colspan = "3"></th>
          </tr>
      </thead>
      <tbody>
       <% @books.each do |book| %>
          <tr>
             <td><%= book.title %></td>
             <td><%= book.body %></td>
             <td><%= link_to "Show", book_path(book.id) %></td>
             <td><%= link_to "Edit", edit_book_path(book.id) %></td>
             <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <h2>New book</h2>
     <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul> 
<% end %>

  <%= form_with model: @book, url: '/books', method: :post, local: true do |f| %>
   <h4>Titel</h4>
   <%= f.text_field :title %>
   <h4>Body</h4>
   <%= f.text_area :body %>
   <p><%= f.submit 'Create Book' %></p>
  <% end %>

  
</body>

app/views/books/new.html.erb
<h1>New book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: '/books', method: :post, local: true do |f| %>
 <h4>Titel</h4>
 <%= f.text_field :title %>
 <h4>Body</h4>
 <%= f.text_area :body %>
 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<body>
 <%= flash[:notice] %>
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
     <strong>Body:</strong>
     <%= @book.body %>
  </p>
</body>

 </br>
 <p>
  <%= link_to "Edit", edit_book_path(@book.id) %>
   |
  <%= link_to "Back", "/books" %>
 </p>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>

<P>印象を共有し交換することができます</P>

<p><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
    <%= yield %>
  </body>
</html>